export type TRegion =
	| 'Europe'
	| 'North America'
	| 'South America'
	| 'Asia'
	| 'Africa'
	| 'Oceania'
	| 'Middle East'
	| 'Caribbean'
	| 'Central America'
	| 'Southeast Asia'
	| 'Eastern Europe'
	| 'Western Europe'
	| 'Northern Europe'
	| 'Southern Europe'
	| 'Western Asia'
